### ISSUE TITLE
Integration with ray

### ISSUE THREAD

**Issue by vijayvammi** [AstraZeneca/magnus-core#25]
Ray as an executor should be possible. 

So trigger_job should be, ray.remote(magnus execute_single_node .. )

**Comment by dynamicwebpaige** [comment]
If this feature request is still of interest, I'd be happy to hop on a call and discuss how / if Ray could help AstraZeneca with `magnus-core`. 👍 

Are you looking to replace some of the functionality in Papermill, @vijayvammi? If yes, it might also be worth taking a look at [Ray Workflows](https://docs.ray.io/en/latest/workflows/concepts.html).
