### ISSUE TITLE
Containerise for local development

### ISSUE THREAD

**Issue by singhsimran39** [AstraZeneca/magnus-core#45]
Developers should be able ti run the project in a containerised environment without the need for creating a virtual environment. 
Acceptance Criteria:
- A containerised environment is created
- Developer should be able to run the project in docker container
- The project root should be mapped to the container so that the develope does not have to rebuild the image when developing and testing locally

Future improvements:
- Image can be built using docker compose

**Comment by vijayvammi** [comment]
Hi Simran, 

Could you explain more?

I am this as one way to set up development environment but not as an issue.

Cheers,
Vijay

**Comment by singhsimran39** [comment]
(sorry did not know if this should not be an issue)
Suppose while going through the sourec code of magnus I found a bug and want to fix it. That would need cloning the repo and pip installing the reqs of the project (this project uses poetry to do that for us, but lets take the `pip install -r` example). Instead if there is a dockerfile available then I can clone the repo and then build and run the docker image without having to do pip install and since the volumes would be mounted I can fix the bug `exec` into the container and run all the unit tests to see that the fix worked. The workflow could look like:
1. `docker build . --tag magnus:latest`
2. `docker run -it --entrypoint=/bin/bash -v $(pwd):/app`
3. From inside  the container change code and run tests using `tox` command with required args

**Comment by vijayvammi** [comment]
I can take that advice as a developer guide in the future. Thanks a lot :-)
